export const INITIALIZE_COLORS = "INITIALIZE_COLORS";
export const ADD_PALETTE_COLOR = "ADD_PALETTE_COLOR";
export const UPDATE_PALETTE_COLOR = "UPDATE_PALETTE_COLOR";
export const DELETE_PALETTE_COLOR = "DELETE_PALETTE_COLOR";
export const UPDATE_SHADE_COLOR = "UPDATE_SHADE_COLOR";
export const UPDATE_ACCESSIBILITY_COLOR = "UPDATE_ACCESSIBILITY_COLOR";
export const SWAP_ACCESSIBILITY_COLORS = "SWAP_ACCESSIBILITY_COLORS";
